FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      harfbuzz \
      ca-certificates \
      ttf-freefont

RUN npm install

COPY . .

# Generate Prisma client during build for dev server to work
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]
