FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

# Generate Prisma client during build for dev server to work
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]
